import Link from "next/link";
import { LEGAL_LAST_UPDATED, PRIVACY_CONTACT, TERMS_VERSION } from "@/lib/legal";

export const dynamic = "force-static";

export default function PrivacyPage() {
  return <main className="mx-auto max-w-[820px] px-4 pb-16 pt-10 lg:px-6"><article className="space-y-8">
    <header className="space-y-2 border-b border-border pb-8"><h1 className="text-2xl font-bold tracking-tight text-fg">Privacy Policy</h1><p className="num text-base text-mute">Last updated: {LEGAL_LAST_UPDATED} · Terms version {TERMS_VERSION}</p><p className="max-w-2xl pt-2 text-md leading-7 text-fg-secondary">This Privacy Policy explains how Pool Party collects, uses, shares, and protects information when you use our social leaderboard and analytics service.</p></header>
    <Section title="1. Who we are and what this covers"><p>Pool Party is an independent community project operated by LP Pool Party. In this Policy, “Pool Party,” “we,” “us,” and “our” mean Pool Party and its operator. This Policy applies to the website, accounts, leaderboard, pool pages, social features, and related services.</p><p>Pool Party is not affiliated with, endorsed by, sponsored by, or otherwise officially connected with Meteora. “Meteora,” Solana, X, and other names and marks belong to their respective owners.</p></Section>
    <Section title="2. Information we collect"><p><strong className="text-fg">Account and identity data.</strong> We collect wallet public addresses, X profile information (handle, name, avatar, and X user ID), and the country you choose. A wallet public address is not a private key; we never ask for or store seed phrases or private keys.</p><p><strong className="text-fg">Community data.</strong> We collect LP ideas and other posts you submit, likes, follows, invite activity, consent records, and account settings.</p><p><strong className="text-fg">Analytics and on-chain data.</strong> We read public blockchain data and data from Meteora APIs, which may include positions, pool activity, PnL, fees, volume, and related public identifiers associated with a wallet. We do not control the public ledger.</p><p><strong className="text-fg">Technical data.</strong> We receive session cookies, IP address, browser and device information, timestamps, request details, security events, and basic server logs. We may receive information from wallet providers, X, Meteora, Solana infrastructure, and hosting or security providers.</p></Section>
    <Section title="3. Why we use information"><ul className="list-disc space-y-2 pl-5"><li>To create and secure accounts, verify wallet control, authenticate through X, and remember your session.</li><li>To show rankings, positions, PnL, fees, pool analytics, profiles, follows, likes, LP ideas, and activity.</li><li>To operate invitations, beta limits, moderation, customer support, troubleshooting, and service communications.</li><li>To detect abuse, fraud, security incidents, sanctions risks, and unlawful use; comply with law; and enforce our Terms.</li><li>To measure reliability, improve features, and maintain backups and business records.</li></ul></Section>
    <Section title="4. Public and private information"><p>Joined-member profiles, X handle and avatar where supplied, chosen country, LP ideas, follows, likes, activity, positions, and PnL or fee statistics may be visible to other visitors. Public output is designed not to display wallet addresses.</p><p>Wallet public addresses are never shown publicly by Pool Party. They are used privately for identification, account operations, and matching public data. Session cookies, IP addresses, logs, private support communications, consent timestamps, and security information are not public, subject to lawful disclosures.</p><p>Because blockchain and third-party data are public or independently controlled, we cannot guarantee that a wallet-related fact can be erased from the blockchain or another provider’s systems.</p></Section>
    <Section title="5. Legal bases"><p>For people in jurisdictions using GDPR-style rules, we process information as needed to perform our agreement with you, with your consent (including Terms and Privacy consent and optional profile choices), for our legitimate interests in security, service operation, analytics, and community features, and to comply with legal obligations. Where we rely on consent, you may withdraw it prospectively, without affecting earlier lawful processing.</p><p>For Philippine users, Pool Party handles personal information consistently with the Philippine Data Privacy Act of 2012 (Republic Act No. 10173), its implementing rules, and applicable National Privacy Commission guidance. We seek consent where required and process information for legitimate, specified, and proportional purposes.</p></Section>
    <Section title="6. Retention and deletion"><p>We keep account and consent records while your account is active and as needed for security, legal, dispute, audit, and legitimate business purposes. We retain LP ideas, follows, likes, and activity while needed to operate the community or until removed under our policies, subject to backups and legal records.</p><p>You may request deletion through {PRIVACY_CONTACT}. We will delete or de-identify information where reasonably possible and legally required, but may retain limited records for fraud prevention, unresolved disputes, legal compliance, backup cycles, or evidence of consent. Public blockchain data and copies held by third parties are outside our control.</p></Section>
    <Section title="7. Sharing and processors"><p>We do not sell personal information. We share information only as needed to run Pool Party, including with Railway for hosting and infrastructure; database, logging, email, security, and support providers; wallet providers for connection and signing; X for OAuth profile authentication; and Meteora, Solana RPC, and related data providers for public pool and on-chain data. These providers process information under their own terms and privacy policies.</p><p>We may disclose information when required by law, legal process, court order, or a valid government request; to protect users, the public, or the service; to investigate abuse; or in a merger, financing, reorganization, or transfer of assets. We may publish aggregated or de-identified statistics that do not reasonably identify you.</p></Section>
    <Section title="8. Security"><p>We use reasonable administrative, technical, and organizational measures appropriate to the information and risks, including access controls, encrypted transport, limited secrets access, session protections, and monitoring. No service, wallet, network, or transmission is perfectly secure. Never send us a private key, seed phrase, password, or signing approval you do not understand.</p></Section>
    <Section title="9. Your choices and rights"><p>Depending on where you live, you may have rights to access, correct, update, delete, restrict, object to, or receive a copy of personal information, and to withdraw consent or complain to a regulator. California residents may have additional CCPA/CPRA-style rights, including to know, correct, delete, and opt out of sale or sharing; Pool Party does not sell personal information.</p><p>Send requests to {PRIVACY_CONTACT}. We may verify identity using account information and will respond within the period required by applicable law. You may also change profile fields in the service or stop optional features. You can sign out at any time; signing out does not erase an account.</p></Section>
    <Section title="10. Cookies and similar technologies"><p>We use an essential, httpOnly session cookie to keep you signed in and security or preference mechanisms needed to operate the service. We may use basic logs and privacy-conscious measurement to understand reliability. We do not use cookies to sell personal information. Your browser can restrict cookies, but sign-in and some features may stop working.</p></Section>
    <Section title="11. International transfers"><p>Pool Party and our providers may process information in the Philippines, the United States, and other countries where providers operate. Those countries may have different privacy protections. Where required, we use appropriate safeguards, contractual protections, or another lawful transfer mechanism.</p></Section>
    <Section title="12. Children and prohibited use"><p>Pool Party is intended for adults and is not directed to children under 18. We do not knowingly collect information from children under 18. If you believe a child provided information, contact {PRIVACY_CONTACT} so we can investigate and remove it where appropriate.</p><p>Do not provide information for a person you are not authorized to represent, and do not use Pool Party for unlawful, sanctioned, fraudulent, or abusive activity.</p></Section>
    <Section title="13. Third parties and non-affiliation"><p>Third parties, including Meteora, Solana, X, wallet providers, and Railway, have their own privacy practices. Pool Party is an independent project and is not affiliated with, endorsed by, or sponsored by Meteora. Meteora and other marks belong to their owners. We are not responsible for third-party collection, security, availability, or deletion practices.</p></Section>
    <Section title="14. Changes and contact"><p>We may update this Policy by publishing a new version and changing the date above. If a change materially affects your rights, we may ask you to accept it before continued sign-in or use. Continued use after an update means the updated Policy applies where permitted by law.</p><p>Questions and privacy requests may be sent to {PRIVACY_CONTACT}.</p></Section>
    <footer className="border-t border-border pt-6 text-base text-mute"><Link href="/terms" className="link">Read the Terms of Service →</Link></footer>
  </article></main>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3"><h2 className="text-lg font-semibold text-fg">{title}</h2><div className="space-y-3 text-md leading-7 text-fg-secondary">{children}</div></section>; }
