import Link from "next/link";
import { Suspense } from "react";
import { TermsGate } from "@/components/TermsGate";
import { LEGAL_LAST_UPDATED, PRIVACY_CONTACT, TERMS_VERSION } from "@/lib/legal";

export const dynamic = "force-static";

export default function TermsPage() {
  return <main className="mx-auto max-w-[820px] px-4 py-10 lg:px-6 lg:py-16"><Suspense fallback={null}><TermsGate /></Suspense><article className="space-y-8">
    <header className="space-y-3 border-b border-border pb-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-accent">Pool Party</p><h1 className="text-3xl font-extrabold tracking-tight text-fg sm:text-4xl">Terms of Service</h1><p className="text-sm text-mute">Last updated: {LEGAL_LAST_UPDATED} · Version {TERMS_VERSION}</p><p className="max-w-2xl text-[15px] leading-7 text-mute">These Terms govern your use of Pool Party, a social leaderboard and analytics service for Meteora liquidity providers. By signing in, joining the beta, or using the service, you agree to these Terms and our <Link href="/privacy" className="font-semibold text-accent hover:underline">Privacy Policy</Link>.</p></header>
    <Section title="1. About Pool Party and acceptance"><p>Pool Party is an independent community project. In these Terms, “Pool Party,” “we,” “us,” and “our” mean the Pool Party service and its operator. “You” means the person using the service.</p><p>These Terms form a binding agreement when you access the service, create an account, sign in, redeem an invite, or otherwise use Pool Party. If you do not agree, do not use the service. If you use Pool Party for an organization, you represent that you can bind that organization.</p><p>Pool Party is not affiliated with, endorsed by, sponsored by, or otherwise officially connected with Meteora. “Meteora,” Solana, X, and other names and marks belong to their respective owners.</p></Section>
    <Section title="2. Eligibility, accounts, and beta access"><p>You must be at least 18 years old and legally able to enter this agreement. You may not use Pool Party if doing so would violate laws that apply to you, including sanctions or export-control laws.</p><p>Beta access may require an invite and may be limited, suspended, or closed at any time. Keep account information accurate. You are responsible for activity through your account and for protecting access to your wallet, X account, and devices.</p><p>Do not create accounts for another person, impersonate anyone, evade a restriction, or use a wallet or identity you do not control.</p></Section>
    <Section title="3. Read-only service; no custody or asset movement"><p>For now, Pool Party is read-only. We read public on-chain data and data made available through Meteora’s public or authorized APIs to display analytics, rankings, pool information, positions, and activity.</p><p>We do not hold private keys, custody funds, take possession of assets, execute trades, provide liquidity, move tokens, or instruct a wallet to do so. A wallet connection identifies an account. A wallet signature is requested only where needed to verify control of that wallet or authorize an account operation; it is not an order or asset-transfer approval.</p><p>Future releases may include in-app liquidity actions, trading, or other transactions. Any such feature would be governed by updated terms, clear disclosures, and explicit opt-in before it is enabled. Nothing in these Terms authorizes a future feature.</p></Section>
    <Section title="4. No financial, investment, or fiduciary advice"><p>Pool Party is an information and community tool, not a broker, exchange, investment adviser, financial planner, tax adviser, fiduciary, or counterparty. Rankings, PnL, fees, win rates, pool data, theses, and other material are not recommendations, offers, solicitations, or guarantees.</p><p>On-chain and API data can be delayed, incomplete, estimated, unavailable, or inaccurate. You are solely responsible for your research and decisions. Consider your objectives, experience, liquidity needs, tax position, and risk tolerance, and do your own research before taking action. Crypto assets and liquidity provision can lose some or all of their value.</p></Section>
    <Section title="5. Crypto risks and prohibited use"><p>You accept blockchain and digital-asset risks, including volatility, impermanent loss, smart-contract bugs, oracle or API failures, validator or network outages, congestion, forks, exploits, phishing, lost keys, irreversible transactions, counterparty failure, changing laws, and tax consequences. We cannot reverse on-chain transactions or recover lost assets.</p><p>You may not use Pool Party for unlawful activity, fraud, market manipulation, money laundering, terrorist financing, sanctions evasion, harassment, scraping that burdens the service, malware, unauthorized access, or infringement. You may not use it from or on behalf of a sanctioned person, entity, or prohibited jurisdiction, or where access is prohibited by law. We may block access or request information to comply with law.</p></Section>
    <Section title="6. User content and conduct"><p>You may post theses and other content where features are available. You retain ownership. You grant Pool Party a worldwide, non-exclusive, royalty-free, transferable, sublicensable license to host, store, reproduce, adapt for formatting, display, and distribute that content to operate, improve, and promote the service.</p><p>You promise you have the rights needed to post it and that it is not unlawful, deceptive, defamatory, threatening, hateful, invasive of privacy, sexually exploitative, infringing, or designed to manipulate or mislead. Do not post private keys, seed phrases, passwords, or sensitive personal data.</p><p>We may, but are not required to, moderate, remove, limit, or preserve content and may suspend or terminate accounts that violate these Terms, harm others, create legal risk, or threaten the service.</p></Section>
    <Section title="7. Third-party services and links"><p>Pool Party relies on third parties, including Meteora data and services, Solana and its public network, X, wallet providers, analytics or infrastructure providers, and Railway hosting. Those services have their own terms, privacy practices, availability, fees, and risks. We do not control and are not responsible for third-party services, content, outages, security, or actions. A link or integration is not an endorsement.</p><p>Pool Party is not affiliated with, endorsed by, or sponsored by Meteora. Meteora and all other third-party marks remain the property of their owners.</p></Section>
    <Section title="8. Intellectual property"><p>Pool Party and its software, design, branding, text, compilation, and non-user content are owned by Pool Party or its licensors and protected by applicable law. Subject to these Terms, we grant you a limited, revocable, non-exclusive, non-transferable right to use the service for personal, lawful purposes. You may not copy, frame, sell, reverse engineer, or create a competing service from it except as law permits.</p></Section>
    <Section title="9. Disclaimers"><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE AND ALL CONTENT ARE PROVIDED “AS IS” AND “AS AVAILABLE.” POOL PARTY DISCLAIMS ALL WARRANTIES, EXPRESS, IMPLIED, AND STATUTORY, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, AVAILABILITY, SECURITY, AND THAT THE SERVICE WILL BE ERROR-FREE OR UNINTERRUPTED.</p><p>We do not promise any return, ranking, uptime, data quality, compatibility, or particular result. Nothing limits rights that cannot lawfully be limited.</p></Section>
    <Section title="10. Liability cap and indemnity"><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, POOL PARTY AND ITS OPERATORS, CONTRIBUTORS, LICENSORS, AND SERVICE PROVIDERS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, LOST PROFITS, LOST DATA, LOST ASSETS, OR LOSS ARISING FROM BLOCKCHAIN OR THIRD-PARTY SERVICES, EVEN IF ADVISED OF THE POSSIBILITY.</p><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE OR THESE TERMS IS LIMITED TO THE GREATER OF US$100 OR THE FEES YOU PAID TO POOL PARTY FOR THE SERVICE DURING THE SIX MONTHS BEFORE THE EVENT. We do not charge for the read-only beta, so this will ordinarily be US$100.</p><p>You will defend, indemnify, and hold harmless Pool Party and its operators, contributors, licensors, and service providers from claims, losses, liabilities, costs, and expenses (including reasonable legal fees) arising from your content, breach of these Terms, unlawful use, or violation of another person’s rights.</p></Section>
    <Section title="11. Suspension, termination, and changes"><p>You may stop using Pool Party at any time. We may suspend or terminate access, remove content, or discontinue all or part of the service at any time, including for security, legal, operational, or beta reasons. Provisions that should survive termination will survive, including ownership, disclaimers, liability limits, indemnity, dispute terms, and governing law.</p><p>We may change these Terms by publishing an updated version and changing the date and version above. Where a change materially affects your rights, we may ask you to accept it before continued sign-in or use. If you do not accept an update, stop using the service.</p></Section>
    <Section title="12. Disputes, arbitration, and class-action waiver"><p>Before filing a claim, contact us at {PRIVACY_CONTACT} and give us 30 days to try to resolve it. Except where prohibited by law or where a court must hear the matter, disputes will be resolved by confidential, individual arbitration in Manila, Philippines, under the Alternative Dispute Resolution Act of 2004 and applicable Philippine arbitration rules. The arbitrator may award the same individual relief a court could award.</p><p>YOU AND POOL PARTY AGREE THAT CLAIMS MAY BE BROUGHT ONLY IN AN INDIVIDUAL CAPACITY, NOT AS A PLAINTIFF OR CLASS MEMBER IN A CLASS, COLLECTIVE, REPRESENTATIVE, OR PRIVATE-ATTORNEY-GENERAL ACTION. The arbitrator may not combine claims or award relief to anyone other than the individual claimant. If this waiver is unenforceable for a particular claim, that claim will proceed in the proper court and the remaining terms remain effective.</p></Section>
    <Section title="13. Governing law and general terms"><p>These Terms are governed by the laws of the Republic of the Philippines, without regard to conflict-of-law rules. Courts in Manila, Philippines have exclusive jurisdiction over matters that cannot be arbitrated, subject to mandatory consumer protections.</p><p>If any provision is unenforceable, it will be limited to the minimum extent necessary and the rest will remain in effect. These Terms, together with the Privacy Policy and feature-specific terms, are the entire agreement about Pool Party and replace prior understandings. A waiver must be written and does not waive a later breach. You may not assign these Terms without our consent; we may assign them in connection with a reorganization or transfer.</p></Section>
    <Section title="14. Contact"><p>Questions, rights requests, and legal notices may be sent to {PRIVACY_CONTACT}. Please include enough information for us to identify the account and understand the request.</p></Section>
    <footer className="border-t border-border pt-6 text-sm text-mute"><Link href="/privacy" className="font-semibold text-accent hover:underline">Read the Privacy Policy →</Link></footer>
  </article></main>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3"><h2 className="text-xl font-bold text-fg">{title}</h2><div className="space-y-3 text-[15px] leading-7 text-mute">{children}</div></section>; }
